#!/usr/bin/env python3
"""Render the README's "Measured behaviour" section from ``results/``.

    python scripts/sync_readme.py            # rewrite the section in place
    python scripts/sync_readme.py --check    # exit 1 if README is out of date

Every number the README quotes about performance is read from the CSV and
JSON files the experiment harness wrote, and the section is regenerated
between two marker comments. Nothing in it is typed by hand, which is the
point: five audit rounds in a row found a throughput figure, a proof timing
or a spread that had been correct when written and stale or imprecise by
the next release. A generated section cannot be stale unless ``results/``
is, and CI runs ``--check`` so it cannot be that either.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DASH = "\u2013"   # en dash, for ranges
TIMES = "\u00d7"  # multiplication sign
BEGIN = "<!-- measured:begin -->"
END = "<!-- measured:end -->"
NOTE = ("<!-- Generated by scripts/sync_readme.py from results/. "
        "Edit the script or re-run the harness; do not edit this by hand. -->")


def _rows(path: Path) -> list[dict[str, Any]]:
    with path.open(newline="", encoding="utf-8") as handle:
        out = []
        for row in csv.DictReader(handle):
            out.append({k: (float(v) if v not in ("", None) and "." in v else
                            (int(v) if v not in ("", None) and v.lstrip("-").isdigit() else v))
                        for k, v in row.items()})
        return out


def _hundreds(n: float) -> str:
    return f"{round(n, -2):,.0f}"


def render(results: Path) -> str:
    """The section text, from the files in ``results``."""
    env = json.loads((results / "environment.json").read_text(encoding="utf-8"))
    thr = _rows(results / "throughput.csv")
    gas = _rows(results / "gas.csv") if (results / "gas.csv").exists() else []
    proof = _rows(results / "proof_size.csv")
    det = _rows(results / "detection.csv")

    runs = int(thr[0].get("runs", 1))
    repeats = int(thr[0].get("repeats", 1))
    a = [r["anchor_records_per_s"] for r in thr]
    v = [r["verify_records_per_s"] for r in thr]
    sizes = (thr[0]["records"], thr[-1]["records"])

    def spreads(kind: str) -> str:
        within = max(float(r.get(f"{kind}_spread", 0)) for r in thr)
        across = max(float(r.get(f"{kind}_run_spread", 0)) for r in thr)
        parts = [f"within-run spread ≤ {within:.0%}"]
        if runs > 1:
            parts.append(f"run-to-run ≤ {across:.0%}")
        return "; " + ", ".join(parts)

    worst_within = max(max(float(r.get("anchor_spread", 0)), float(r.get("verify_spread", 0)))
                       for r in thr)
    worst_across = max(max(float(r.get("anchor_run_spread", 0)),
                           float(r.get("verify_run_spread", 0))) for r in thr)

    big = max(proof, key=lambda r: r["batch_size"])
    injected = sum(int(r["injected"]) for r in det)
    fps = sum(int(r["false_positives"]) for r in det)
    recall = min(float(r[k]) for r in det for k in r if k.endswith("_recall"))

    machine = ", ".join(x for x in (
        f"CPython {env.get('python')}",
        (f"{env['cpu_count']}-core " if env.get("cpu_count") else "") + "x86-64 Linux VM"
        if "Linux" in env.get("platform", "") else env.get("platform", ""),
        env.get("cpu_model"),
    ) if x)
    stats = (f"medians across {runs} runs {TIMES} {repeats} repeats" if runs > 1
             else f"medians of {repeats} repeats")

    prose = (
        f"Reproduce with `python scripts/experiments.py --runs {runs}`; the "
        "environment is recorded alongside the results. Every throughput row "
        f"carries its within-run spread (across the {repeats} timed repeats)"
        + (f" and its run-to-run spread (across the {runs} consecutive runs in "
           "`results/throughput_runs.csv`)." if runs > 1 else ".")
        + " On the machine the shipped numbers come from, within-run spread "
        f"reaches {worst_within:.0%}"
        + (f" and run-to-run spread {worst_across:.0%}" if runs > 1 else "")
        + " -- larger than any effect of ledger size -- so re-run on your own "
        "hardware before quoting absolute rates."
    )
    lines = [
        BEGIN, NOTE, "",
        *textwrap.wrap(prose, width=78, break_on_hyphens=False),
        "",
        f"| Property | Measurement (`results/`, v{env.get('ledgerguard_version')}, {machine}; {stats}) |",
        "|---|---|",
        f"| Anchoring throughput | {_hundreds(min(a))}{DASH}{_hundreds(max(a))} records/s from "
        f"{sizes[0]:,} to {sizes[1]:,} records, no trend with size{spreads('anchor')} |",
        f"| Verification throughput | {_hundreds(min(v))}{DASH}{_hundreds(max(v))} records/s with full "
        f"witness replay, no trend with size{spreads('verify')} |",
        "| Committed per batch | one 32-byte digest, independent of batch size |",
    ]
    if gas:
        g = [int(r["gas_used"]) for r in gas]
        lines.append(
            f"| Gas per anchoring transaction | {min(g):,}{DASH}{max(g):,} across batches of "
            f"{min(int(r['batch_size']) for r in gas):,}{DASH}{max(int(r['batch_size']) for r in gas):,} "
            f"records; first anchor on a fresh registry {int(gas[0]['first_anchor_gas']):,} |")
    lines += [
        f"| Inclusion proof | {int(big['proof_hashes'])} hashes ({int(big['proof_bytes'])} B) at "
        f"{int(big['batch_size']):,} records; verify in ~{float(big['verify_us']):.0f} µs |",
        f"| Detection | {injected:,} injected manipulations over {len(det)} seeded runs: "
        f"{recall:.0%} recall on all four attack classes, {fps} false positive"
        f"{'' if fps == 1 else 's'} |",
        END,
    ]
    return "\n".join(lines)


def apply(readme: str, section: str) -> str:
    start, stop = readme.index(BEGIN), readme.index(END) + len(END)
    return readme[:start] + section + readme[stop:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=ROOT / "results")
    parser.add_argument("--readme", type=Path, default=ROOT / "README.md")
    parser.add_argument("--check", action="store_true",
                        help="report whether the README matches results/, without writing")
    args = parser.parse_args()

    current = args.readme.read_text(encoding="utf-8")
    if BEGIN not in current or END not in current:
        print(f"{args.readme} has no {BEGIN} / {END} markers", file=sys.stderr)
        return 2
    wanted = apply(current, render(args.results))
    if args.check:
        if wanted == current:
            print("README measured-behaviour section matches results/")
            return 0
        print("README measured-behaviour section is out of date; run "
              "scripts/sync_readme.py", file=sys.stderr)
        return 1
    args.readme.write_text(wanted, encoding="utf-8")
    print(f"rewrote the measured-behaviour section of {args.readme.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
